### ISSUE TITLE
Update for ROS 2 Galactic

### ISSUE THREAD

**Issue by ljaniec** [Adlink-ROS/BT_ros2#6]
Hello,

I would like to know if there are any plans to update the repository with the ROS Galaxy version? 

Right now I'm  having trouble building everything without any deeper changes.

Best regards
Łukasz Janiec

**Comment by QQting** [comment]
Fixed! 
See https://github.com/Adlink-ROS/BT_ros2/commit/a8e31d1e5fccb2d34b8a5646529fc442d1b566b5
